presentation/Store.Web/Models/Cart.cs
namespace Store.Web.Models
{
    public class Cart
    {
        public int OrderId { get; }
        public int TotalCount { get; set; }
        public decimal TotalPrice { get; set; }
        
        public Cart(int id)  
        {
            this.OrderId = id;
            TotalCount = 0;
            TotalPrice = 0m;
        }
    }
}

presentation/Store.Web/Models/ErrorViewModel.cs
namespace Store.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

presentation/Store.Web/Models/OrderItemModel.cs
namespace Store.Web.Models
{
    public class OrderItemModel
    {
        public int BookId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public int Count { get; set; }
        public decimal Price { get; set; }
    }
}

presentation/Store.Web/Models/OrderModel.cs
namespace Store.Web.Models
{
    public class OrderModel
    {
        public int Id { get; set; }
        public OrderItemModel[] Items { get; set; } = new OrderItemModel[0];
        public int TotalCount { get; set; }
        public decimal TotalPrice { get; set; }
    }
}

presentation/Store.Web/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;

namespace Store.Web.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository bookRepository;

        public BookController(IBookRepository bookRepository)
        {
            this.bookRepository = bookRepository;
        }

        public IActionResult Index(int id)
        {
            return View(bookRepository.GetById(id));
        }
    }
}

presentation/Store.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Web.Models;
using System.Diagnostics;

namespace Store.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

presentation/Store.Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Web.Models;
using System.Security.Permissions;

namespace Store.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IBookRepository bookRepository;
        private readonly IOrderRepository orderRepository;

        public OrderController(IBookRepository bookRepository, IOrderRepository orderRepository)
        {
            this.bookRepository = bookRepository;
            this.orderRepository = orderRepository;
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.TryGetCart(out Cart cart))
            {
                Order order = orderRepository.GetById(cart.OrderId);
                OrderModel model = new OrderModel();

                model.Items = new OrderItemModel[order.Items.Count];

                var bookIds = order.Items.Select(item => item.BookId).ToArray();
                Book[] books = bookRepository.GetAllByIds(bookIds);

                for (int i = 0; i != order.Items.Count; ++i)
                {
                    int bookId = order.Items.ElementAt(i).BookId;
                    Book book = books.Single(item => item.Id == bookId);
                    
                    model.Items[i] = new OrderItemModel()
                    {
                        BookId = bookId,
                        Author = book.Author,
                        Title = book.Title,
                        Count = order.Items.ElementAt(i).Count,
                        Price = order.Items.ElementAt(i).Price,
                    };
                }

                model.TotalPrice = order.TotalPrice;
                model.TotalCount = order.TotalCount;
                return View(model);
            }
            return View("Empty");
        }


        [HttpPost]
        public IActionResult EditBook(int bookId, int count)
        {
            GetOrCreateOrderAndCart(out Order order, out Cart cart);
            order.Get(bookId).Count += count;
            orderRepository.Update(order);
            SaveOrderAndCart(order, cart);
            return RedirectToAction("Index", "Order");
        }

        [HttpPost]
        public IActionResult AddItem(int bookId, int count)
        {
            GetOrCreateOrderAndCart(out Order order, out Cart cart);
            Book book = bookRepository.GetById(bookId);
            if (order.ContainsBook(bookId) == true)
            {
                order.Get(bookId).Count += count;
            }
            else
            {
                order.AddNewBook(book);
            }
            SaveOrderAndCart(order, cart);
            return RedirectToAction("Index", "Book", new { id = bookId });
        }

        public IActionResult RemoveItem(int bookId)
        {
            GetOrCreateOrderAndCart(out Order order, out Cart cart);
            Book book = bookRepository.GetById(bookId);
            order.RemoveItem(book);
            orderRepository.Update(order);
            SaveOrderAndCart(order, cart);
            return RedirectToAction("Index", "Order");
        }

        private void SaveOrderAndCart(Order order, Cart cart)
        {
            cart.TotalCount = order.TotalCount;
            cart.TotalPrice = order.TotalPrice;
            HttpContext.Session.Set(cart);
        }

        private void GetOrCreateOrderAndCart(out Order order, out Cart cart)
        {
            if (HttpContext.Session.TryGetCart(out cart))
            {
                order = orderRepository.GetById(cart.OrderId);
            }
            else
            {
                order = orderRepository.Create();
                cart = new Cart(order.Id);
            }
        }
    }
}

presentation/Store.Web/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;

namespace Store.Web.Controllers
{
    public class SearchController : Controller
    {
        private BookService bookService;

        public SearchController(BookService bookService)
        {
            this.bookService = bookService;
        }

        public IActionResult Index(string query)
        {
            var books = bookService.GetAllByQuery(query);
            return View(books);
        }
    }
}

presentation/Store.Web/Views/Book/Empty.cshtml

@{
    ViewData["Title"] = "Orders";
}

<h1>Empty</h1>


presentation/Store.Web/Views/Book/Index.cshtml
@model Book

@{
    ViewData["Title"] = Model.Title;
}

<h1>@Model.Title</h1>
<p><strong>@Model.Author</strong></p>
<p>@Model.Description</p>
<p><strong>Price:  @Model.Price$</strong></p>
<form action="@Url.Action("AddItem", "Order")" method="post">
    <input type="hidden" name="bookId" value="@Model.Id" />
    <input type="hidden" name="count" value="1" />
    <button class="btn btn-success" type="submit">Buy</button>
</form> 

presentation/Store.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Online Store";
}

presentation/Store.Web/Views/Order/Index.cshtml
@model OrderModel

@{
    ViewData["Title"] = "Orders";
}

<h1>@ViewData["Title"]</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">Amount</th>
            <th scope="col">Price</th>
            <th scope="col">Edit</th>
            <th scope="col">Remove</th>
        </tr>
    </thead>
    @foreach (var item in Model.Items)
    {
        <tr>
            <td scope="row">@item.Title</td>
            <td scope="row">@item.Author</td>
            <td scope="row">@item.Count</td>
            <td scope="row">@item.Price</td>
            <form action="@Url.Action("EditBook", "Order")" method="post">
                <input type="hidden" name="bookId" value="@item.BookId" />
                <input type="hidden" name="count" value="1" />
                <td scope="row"><button type="submit" class="btn btn-success">Edit</button></td>
            </form>
            
            <form action="@Url.Action("RemoveItem", "Order")" method="post">
                <input type="hidden" name="bookId" value="@item.BookId" />
                <td scope="row"><button type="submit" class="btn btn-danger">Remove</button></td>
            </form>
        </tr>
    }
</table>

<p>Total Amount @Model.TotalCount</p>
<p>Total Price @Model.TotalPrice</p>

presentation/Store.Web/Views/Search/Index.cshtml
@model Book[]

@{
    ViewData["Title"] = "Search Result";
}

<h1>Search Result</h1>

@if (Model.Length == 0)
{
    <p>Results Not Found</p>
}
else
{
    <ul>
        @foreach(var book in Model)
        {
            <li><a href="@Url.Action("Index", "Book", new {id = book.Id})">@book.Title</a></li>
        }
    </ul>
}

presentation/Store.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Online Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Store.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Online Store</a>
            <form class="form-inline d-flex my-2 my-lg-0" action="@Url.Action("Index", "Search")" method="get">
                <input class="form-control mr-sm-2" type="search" name="query" placeholder="name or title" />
                <button class="btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <span class="navbar-text d-flex ml-2">
                @{
                    Cart cart;

                    if (Context.Session.TryGetCart(out cart) && cart.TotalCount > 0)
                    {
                        <a href="@Url.Action("Index", "Order")">Amount: @cart.TotalCount Price: @cart.TotalPrice</a>
                    }
                    else
                    {
                        @:Empty
                    }
                }
            </span>
        </nav>
    </header>
    <div class="container">
        <main>
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>